### Authorization protocol fragment, based on OAuth2 (RFC 6749).
###
### Copyright 2021 Julia Gabet <j.gabet18 @ imperial.ac.uk>
### Released under the MIT License: https://opensource.org/licenses/MIT

## p = server
## q = client
## r = authenticator

( s[p][q]<|{login.s[p][r](S)auth(x@Bool).0, cancel.0} | 
( s[q][p](S){login.s[q][r]<|passwd.0, cancel.s[q][r]<|quit.0} | 
s[r][q](S){passwd.s[r][p]<|auth(true@Bool).0, quit.0} ))
